apiVersion: v1
kind: Pod
metadata:
  name: single-pod
spec:

  containers:

  - name: my-awesome-app
    image: 10.101.91.182:5000/my-awesome-app:0.0.1
    volumeMounts:
    - name: shared-data
      mountPath: /var/www/app/config

  - name: echo-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo title=\"Looks like sharing volumes and network between containers works\" > /pod-data/config.ini"]

  - name: curl-container
    image: yauritux/busybox-curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hi; done"]

  volumes:
  - name: shared-data
    emptyDir: {}

  restartPolicy: Never
